---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.0.0
  - name: community.general
    version: 8.1.0
  - name: community.sops
    version: 1.6.7
  - name: community.docker
    version: 3.4.8

roles:
  - name: geerlingguy.docker
    version: 7.0.2
