# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

env:
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/secrets/age.key"

vars:
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  SECRETS_DIR: "{{.ROOT_DIR}}/secrets"

includes:
  ansible: .taskfiles/AnsibleTasks.yaml
  bootstrap: .taskfiles/BootstrapTasks.yaml
  precommit: .taskfiles/PrecommitTasks.yaml
  sops: .taskfiles/SopsTasks.yaml

tasks:
  default:
    desc: List all tasks
    cmd: task --list-all
