---

- name: Time Syncd | Check vars
  ansible.builtin.fail:
    msg: variable 'ntp_server' not defined
  when:
    - ntp_server is not defined
    - ntp_server | length == 0

- name: Time Syncd | Install package
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present

- name: Time Syncd | Copy configuration file
  ansible.builtin.copy:
    content: |
      #  This file is part of systemd.
      #
      #  systemd is free software; you can redistribute it and/or modify it under the
      #  terms of the GNU Lesser General Public License as published by the Free
      #  Software Foundation; either version 2.1 of the License, or (at your option)
      #  any later version.
      #
      # Entries in this file show the compile time defaults. Local configuration
      # should be created by either modifying this file, or by creating "drop-ins" in
      # the timesyncd.conf.d/ subdirectory. The latter is generally recommended.
      # Defaults can be restored by simply deleting this file and all drop-ins.
      #
      # See timesyncd.conf(5) for details.
      [Time]
      NTP={{ ntp_server }}
      FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
      #RootDistanceMaxSec=5
      #PollIntervalMinSec=32
      #PollIntervalMaxSec=2048
      #ConnectionRetrySec=30
      #SaveIntervalSec=60
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
  register: _timesync_configure

- name: Time Syncd | restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
  changed_when: _timesync_configure.changed
