---
- name: Bitwarden | Verify required vars are set
  ansible.builtin.assert:
    that:
      - item in vars
      - vars[item] != ""
    success_msg: Required var {{ item }} exists and is defined
    fail_msg: Required var {{ item }} does not exists or is not defined
  loop:
    - dockerapp_bitwarden_app_smtp_host
    - dockerapp_bitwarden_app_smtp_port
    - dockerapp_bitwarden_app_smtp_security
    - dockerapp_bitwarden_app_smtp_from
    - dockerapp_bitwarden_app_smtp_username
    - dockerapp_bitwarden_app_smtp_password

- name: Bitwarden | Ensure data directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ dockerapp_bitwarden_app_dir }}"

- name: Bitwarden | Deploy
  community.docker.docker_container:
    image: docker.io/vaultwarden/server:1.30.1
    name: bitwarden-app
    recreate: "{{ dockerapp_bitwarden_app_recreate }}"
    restart: "{{ dockerapp_bitwarden_app_restart }}"
    restart_policy: always
    env:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "{{ dockerapp_bitwarden_app_signups_allowed }}"
      INVITATIONS_ALLOWED: "false"
      DOMAIN: "https://{{ dockerapp_bitwarden_app_domain }}"
      # smtp
      SMTP_HOST: "{{ dockerapp_bitwarden_app_smtp_host }}"
      SMTP_PORT: "{{ dockerapp_bitwarden_app_smtp_port }}"
      SMTP_SECURITY: "{{ dockerapp_bitwarden_app_smtp_security }}"
      SMTP_FROM: "{{ dockerapp_bitwarden_app_smtp_from }}"
      SMTP_USERNAME: "{{ dockerapp_bitwarden_app_smtp_username }}"
      SMTP_PASSWORD: "{{ dockerapp_bitwarden_app_smtp_password }}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "{{ dockerapp_bitwarden_app_dir }}:/data"
    networks:
      - name: "{{ dockerapp_ingress_network }}"
    healthcheck:
      test: "curl -f localhost:80 || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      # routers
      traefik.http.routers.bitwarden-app.rule: "Host(`{{ dockerapp_bitwarden_app_domain }}`)"
      traefik.http.routers.bitwarden-app.entrypoints: "web,websecure"
      traefik.http.routers.bitwarden-app.service: "bitwarden-app@docker"
      traefik.http.routers.bitwarden-app-ws.rule: "Host(`{{ dockerapp_bitwarden_app_domain }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.bitwarden-app-ws.entrypoints: "web,websecure"
      traefik.http.routers.bitwarden-app-ws.service: "bitwarden-app-ws@docker"
      # services
      traefik.http.services.bitwarden-app.loadbalancer.server.port: "80"
      traefik.http.services.bitwarden-app-ws.loadbalancer.server.port: "3012"
