---
- name: Ensure data root directory exist
  ansible.builtin.file:
    state: directory
    path: "{{ dockerapp_data_dir }}"
    mode: "0644"

- name: Traefik
  ansible.builtin.include_tasks: traefik.yaml
  args:
    apply:
      tags: always
  tags: always

- name: AdguardHome
  ansible.builtin.include_tasks: adguardhome.yaml
  args:
    apply:
      tags: adguardhome
  tags: never,adguardhome

- name: Bitwarden
  ansible.builtin.include_tasks: bitwarden.yaml
  args:
    apply:
      tags: bitwarden
  tags: never,bitwarden
